#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SelfEducation.Android.Resource", IsApplication=true)]

namespace SelfEducation.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::SelfEducation.Android.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::SelfEducation.Android.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int collor_arrays = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int blue = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int frosty_sky = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int orange = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int white = 2131034115;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int default_button_backgroung = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int gradient_backgroung_app = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int radioButtonBackground = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int RadioButtonChecked = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int RadioButtonPressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int RadioButtonUnChecked = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080006
			public const int LogIn = 2131230726;
			
			// aapt resource value: 0x7f080012
			public const int NextStep = 2131230738;
			
			// aapt resource value: 0x7f080001
			public const int Row = 2131230721;
			
			// aapt resource value: 0x7f080009
			public const int SelectDept = 2131230729;
			
			// aapt resource value: 0x7f080011
			public const int editHeightCabinetArea = 2131230737;
			
			// aapt resource value: 0x7f080003
			public const int editTextEmail = 2131230723;
			
			// aapt resource value: 0x7f080005
			public const int editTextPass = 2131230725;
			
			// aapt resource value: 0x7f080010
			public const int editWidthCabinetArea = 2131230736;
			
			// aapt resource value: 0x7f080000
			public const int layoutContainer = 2131230720;
			
			// aapt resource value: 0x7f080007
			public const int linearLayout1 = 2131230727;
			
			// aapt resource value: 0x7f08000f
			public const int radioLegs = 2131230735;
			
			// aapt resource value: 0x7f08000e
			public const int radioSolidBase = 2131230734;
			
			// aapt resource value: 0x7f08000b
			public const int radioThirtyDep = 2131230731;
			
			// aapt resource value: 0x7f08000a
			public const int radioTwentyFourDep = 2131230730;
			
			// aapt resource value: 0x7f08000c
			public const int spinner = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int textSelectBottoms = 2131230733;
			
			// aapt resource value: 0x7f080008
			public const int textSelectCabinetDepth = 2131230728;
			
			// aapt resource value: 0x7f080002
			public const int textViewEmail = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int textViewPass = 2131230724;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ActionScreen = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int SetupQuestionnaire = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f04000a
			public const int CabinetAreaDimensions = 2130968586;
			
			// aapt resource value: 0x7f040002
			public const int Email = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int EnterEmails = 2130968582;
			
			// aapt resource value: 0x7f040010
			public const int Height = 2130968592;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f04000c
			public const int Legs = 2130968588;
			
			// aapt resource value: 0x7f040005
			public const int NextStep = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int Pass = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int SelectBottoms = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int SelectCabinetDepth = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int SelectCollor = 2130968584;
			
			// aapt resource value: 0x7f04000b
			public const int SolidBase = 2130968587;
			
			// aapt resource value: 0x7f04000e
			public const int ThirtyDep = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public const int TwentyFourDep = 2130968589;
			
			// aapt resource value: 0x7f040011
			public const int Width = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int X = 2130968594;
			
			// aapt resource value: 0x7f04000f
			public const int collor_prompt = 2130968591;
			
			// aapt resource value: 0x7f040004
			public const int logIn = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int CustomButton = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int MyCustomTheme = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
